# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://s01.oss.sonatype.org/content/groups/staging/
        username: ${{ secrets.OSSRH_USERNAME }}
        password: ${{ secrets.OSSRH_PASSWORD }}
        format: maven2
        repository: maven-releases
        coordinates: groupId=io.harness artifactId=ff-java-server-sdk version=1.0.0
        assets: extension=jar
        filename: ./target/app-1.0.0.jar

