name: PR Maven Package

on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn package --file pom.xml
      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://s01.oss.sonatype.org
          username: ${{ secrets.OSSRH_USERNAME }}
          password: ${{ secrets.OSSRH_PASSWORD }}
          format: maven2
          repository: maven-snapshots
          coordinates: groupId=io.harness artifactId=ff-java-server-sdk version=1.1.3-SNAPSHOT
          assets: extension=jar
          filename: ./target/ff-java-server-sdk-1.1.3-SNAPSHOT.jar